apiVersion: ENC[AES256_GCM,data:CNs=,iv:6AkY+6t/+69vfre0aTGvAzrpi4YCXkA9N9TmtE+E3Bs=,tag:GDvwNFeJOBgvlfSxYzvU7A==,type:str]
kind: ENC[AES256_GCM,data:2u614pYm,iv:uvToBbecYQDVTvy8mJ7KpNA7mgDe2HOEbMK7c+k/Yv8=,tag:s20Re2o3GbSRjTSrWx0SQA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Ch5Kcr+h6leqmKGq6IyBrg==,iv:mSvZx2enNVL2wpiHwQShDFN+VRnso2rTQg5dpSkz4R0=,tag:zHfF3ZIGb2vl0yW9UyVhrQ==,type:str]
    namespace: ENC[AES256_GCM,data:rxua,iv:22j6td5IWHjuqBS0i7yo1e07CiFwC2nL1Kv4NwqKsUQ=,tag:3ejGf/kl+H8wFI1hIs1tgw==,type:str]
type: ENC[AES256_GCM,data:fVAVRPJ6,iv:dLHoXqEyfTbbcrHILUEfDTdBhVbu6W6AcO7ndCxhgDQ=,tag:rOU5uUMlyE70BwjrDBK8DA==,type:str]
stringData:
    google-client-id: ENC[AES256_GCM,data:kLS0A815J1Fpm9jUJyRLKmE5WIe2680lFd3jBryuj4j2tl1J3iZfeMJBfb8h5/W+9+DvENMr6HBqkPTrteKVPEicW/jMLPEz,iv:yzTXKCyNOn5b2RsUNcDJLHT9/c5pdwE/6kUjRSCP3DA=,tag:rE7hvPCxSOIUz+xFCXe/6g==,type:str]
    google-client-secret: ENC[AES256_GCM,data:EW7qLvRTYM+MSYRA08ycRSLPJ8ykuGTBNUkMqrU5wT5dN1g=,iv:EVRrJKSCw8MxijPgdJDupJiFDIgCdJBnZpJ0ZsuVDRY=,tag:oePOGE1SBEMV5V72gIYtXg==,type:str]
    argocd-oidc-client-secret: ENC[AES256_GCM,data:7+b9eKqmOaFa0U92I4Ho93hPjtq3L6uMXkYi+is4kyiD/PILmQUwi3UPDODH1cGVkEdE5pJSJhcQjch7veOgig==,iv:bl6hNaTl1m32PgkNoHjkkadowtCByvRwh15I6/I40w8=,tag:p3CzfqFDMVP1+/YJM1PTvQ==,type:str]
    argo-workflows-oidc-client-secret: ENC[AES256_GCM,data:8NmkkO42F4K8kjy+sKceNIN+X8kITjvpu3PoAQSB3C3Bc6B7vdJkS3Wle7AC0UqyoC7JNATE/xtKrGvxt+w/qA==,iv:Eanj9rlpfUnjgfx0QNtHdqZiAONp6zPMVDMC67tX5FQ=,tag:i8HALXP+Yrw0vuU0I8wX3w==,type:str]
    grafana-oidc-client-secret: ENC[AES256_GCM,data:8znrSWXlBvIx+KNvpXl1ZakLqh7jQh6fJK1f3HFK5jyCAbXxSLmVd1+/xA==,iv:hge1x7zcnXBV3wBfVtcN5ZtCF/tSw8S3Q3mEYnvp/0o=,tag:VSv8y8iS5cBBoOErOLvNtw==,type:str]
    prometheus-oidc-client-secret: ENC[AES256_GCM,data:zuDjoNZCvdv7/ZAXIyiYJ2fJuTpeffmMZUcNNxTmoU9P0w7Mss8vbWrvDiYCGqmJxNXjtvKtTcYPcmN95QAgcw==,iv:sXq4EU/yBwtv9+48+pt9hcglx50rJVth96AT4YjCkwk=,tag:ZI9GJmN5XmGWqBHnTSqqcg==,type:str]
    alertmanager-oidc-client-secret: ENC[AES256_GCM,data:PgXKpiguOtgg8+lvxKI2vhJNDSsDs+gCP9Ax/VYr2oLSRY9m2wFzPJtTkNy4h88GJ/8mFIHpDnGvP1pUpunzrQ==,iv:0Q46ieKDO26B4jivxkwyA8D076e0KaPRIOVKsFeYTYg=,tag:TbigtHeAWgCEO96eYqH3xw==,type:str]
sops:
    age:
        - recipient: age1t7jy2m2pqwnwfhx0dk85trhw9aae9qln9ng6m4tgy47jk3ngr93spv0hsg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtbXBjRksyZHNTbkJKeWw2
            SnZNczM4RXZyanpaRTZhVFE3ZXArQVM0bmtjCmRhMHpvbmVEZmh4YmorMU4zajZ1
            MHlubnVCU21VQ2xwbE9DeFlFQjlCbVUKLS0tIHBZaUxyRDNUN1JQOFUva1Nza1lu
            djlKbXBDOHc1L2UxMXJUTnJ5M01KS2sKhw7v9DJ4xJ1sVTcCkQfEUhk81SpG11uR
            m32uYJl0HwyffAjifOTdtZI88ZbS51hoi5wfYZrBe9cNKnjIzHa5KA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T20:33:51Z"
    mac: ENC[AES256_GCM,data:0jrPdwvq4w5e7ENYd0cX6KnPWgcQsSkitNrZ6s80jiVGEC0oJ/FOpyvf4Iu+gmE68amS4vq0Jbafn6vBRCYhCKr8kAsutwvDyHtKDPTIUPtjdACptOJ62KZpu9VMRea9WXf6b5BisDSKX8VbHfttrSeUOkBcLkshW4REajY7K8c=,iv:VwBW2Z533NhFmqdSVv2hcBorc/fvmIRxy37UjITebA4=,tag:uisdhtyHpycP9HXFdQnD0Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
