apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: homelab-staging
spec:
  acme:
    email: thomas.krahn.tk@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: homelab-staging-account-key
    solvers:
      - dns01:
          cloudDNS:
            project: io-ntbc-domain-control-1900413
            serviceAccountSecretRef:
              key: service-account-key.json
              name: google-cloud-dns
        selector:
          dnsZones:
            - homelab.ntbc.io
