apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd
  - piraeus-operator
  - metrics-server
  - cert-approver
  - cert-manager
  - nvidia-device-plugin
  - node-feature-discovery
  - metallb
  - gateway-api
  - dex
