apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - tls.yaml
  - linstor-cluster.yaml
  - linstor-satellite-configuration.yaml
  - storage-class.yaml
  - storage-pool-autovg.yaml
  - monitoring.yaml
