apiVersion: v1
kind: Service
metadata:
  name: drbd-reactor
  namespace: piraeus-datastore
  labels:
    app: drbd-reactor
spec:
  ports:
    - name: metrics
      port: 9942
      targetPort: 9942
  selector:
    app.kubernetes.io/component: linstor-satellite
    app.kubernetes.io/instance: homelab
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: drbd-reactor
  namespace: piraeus-datastore
  labels:
    monitoring: default
spec:
  selector:
    matchLabels:
      app: drbd-reactor
  namespaceSelector:
    matchNames:
      - piraeus-datastore
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: linstor-csi-nfs
  namespace: monitoring
  labels:
    monitoring: default
spec:
  namespaceSelector:
    matchNames:
      - piraeus-datastore
  selector:
    matchLabels:
      app.kubernetes.io/component: linstor-csi-nfs
  endpoints:
    - port: metrics
      interval: 30s
