apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homelab-wildcard-tls
  namespace: default
spec:
  secretName: homelab-wildcard-tls
  issuerRef:
    name: homelab
    kind: ClusterIssuer
  dnsNames:
    - "*.homelab.ntbc.io"
