apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dex
  namespace: argocd
spec:
  project: infrastructure
  sources:
    - repoURL: https://charts.dexidp.io
      chart: dex
      targetRevision: 0.24.*
      helm:
        valueFiles:
          - $values/kubernetes/base/infrastructure/dex/values.yaml
    - repoURL: https://github.com/Nosmoht/Talos-Homelab.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/Nosmoht/Talos-Homelab.git
      targetRevision: HEAD
      path: kubernetes/overlays/homelab/infrastructure/dex/resources
  destination:
    server: https://kubernetes.default.svc
    namespace: dex
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
